
-- Generated by ORDS REST Data Services 26.1.2.r1401916
-- Schema: MIGO_USER  Date: Mon Jun 08 05:53:11 2026 
--
        
DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'migo_user',
      p_auto_rest_auth      => TRUE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'colonias_api',
      p_base_path      => '/colonias/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'colonias_api',
      p_pattern        => 'colonias',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'colonias_api',
      p_pattern        => 'colonias',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT id_colonia, nombre_colonia
FROM colonias
ORDER BY nombre_colonia');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'colonias_api',
      p_pattern        => 'colonias',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'INSERT INTO COLONIAS (NOMBRE_COLONIA) VALUES (:NOMBRE_COLONIA);');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'colonias_api',
      p_pattern        => 'colonias/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'colonias_api',
      p_pattern        => 'colonias/:id',
      p_method         => 'GET',
      p_source_type    => 'json/item',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM COLONIAS WHERE ID_COLONIA=:id');

  ORDS.DEFINE_MODULE(
      p_module_name    => 'especies_api',
      p_base_path      => '/especies/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'especies_api',
      p_pattern        => 'especies',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'especies_api',
      p_pattern        => 'especies',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM ESPECIES');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'especies_api',
      p_pattern        => 'especies',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'INSERT INTO ESPECIES (NOMBRE) VALUES (:NOMBRE);');

  ORDS.DEFINE_MODULE(
      p_module_name    => 'estados_publi_api',
      p_base_path      => '/estados_publi/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'estados_publi_api',
      p_pattern        => 'estados_publi',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'estados_publi_api',
      p_pattern        => 'estados_publi',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM ESTADOS_PUBLI');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'estados_publi_api',
      p_pattern        => 'estados_publi',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'INSERT INTO ESTADOS_PUBLI (NOMBRE) VALUES (:NOMBRE);');

  ORDS.DEFINE_MODULE(
      p_module_name    => 'fotos_publi_api',
      p_base_path      => '/fotos_publi/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'fotos_publi_api',
      p_pattern        => 'publicaciones/:id/fotos',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fotos_publi_api',
      p_pattern        => 'publicaciones/:id/fotos',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_id_publi NUMBER;
    v_error VARCHAR2(4000);
BEGIN
    OWA_UTIL.mime_header(''application/json'', FALSE);
    HTP.p(''Access-Control-Allow-Origin: *'');
    HTP.p(''Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS'');
    HTP.p(''Access-Control-Allow-Headers: Content-Type'');
    OWA_UTIL.http_header_close;

    v_id_publi := :id;

    FOR rec IN (
        SELECT id_foto, id_publi, ruta_imagen, fecha_carga
        FROM fotos_publi
        WHERE id_publi = v_id_publi
          AND ROWNUM = 1
    ) LOOP
        APEX_JSON.open_object;
        APEX_JSON.write(''id_foto'', rec.id_foto);
        APEX_JSON.write(''id_publi'', rec.id_publi);
        APEX_JSON.write(''ruta_imagen'', rec.ruta_imagen);
        APEX_JSON.write(''fecha_carga'', TO_CHAR(rec.fecha_carga, ''YYYY-MM-DD HH24:MI:SS''));
        APEX_JSON.close_object;
    END LOOP;

EXCEPTION
    WHEN OTHERS THEN
        v_error := SQLERRM;
        HTP.p(''{"status":"error","message":"'' || v_error || ' || '''"}'');
END;');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fotos_publi_api',
      p_pattern        => 'publicaciones/:id/fotos',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_error VARCHAR2(4000);
BEGIN
    OWA_UTIL.mime_header(''application/json'', FALSE);
    HTP.p(''Access-Control-Allow-Origin: *'');
    OWA_UTIL.http_header_close;

    APEX_JSON.open_array;
    FOR rec IN (
        SELECT p.id_publi,
               p.id_usuario,
               p.id_colonia,
               p.id_especie,
               p.id_tipo,
               p.nombre_pet,
               p.descripcion,
               p.fecha_publi,
               -- 🔹 Subconsulta: trae la primera foto asociada
               (SELECT f.ruta_imagen
                  FROM fotos_publi f
                 WHERE f.id_publi = p.id_publi
                   AND ROWNUM = 1) AS ruta_imagen
        FROM publicaciones p
        ORDER BY p.fecha_publi DESC
    ) LOOP
        APEX_JSON.open_object;
        APEX_JSON.write(''id_publi'', rec.id_publi);
        APEX_JSON.write(''id_usuario'', rec.id_usuario);
        APEX_JSON.write(''id_colonia'', rec.id_colonia);
        APEX_JSON.write' || '(''id_especie'', rec.id_especie);
        APEX_JSON.write(''id_tipo'', rec.id_tipo);
        APEX_JSON.write(''nombre_pet'', rec.nombre_pet);
        APEX_JSON.write(''descripcion'', rec.descripcion);
        APEX_JSON.write(''fecha_publi'', TO_CHAR(rec.fecha_publi, ''YYYY-MM-DD HH24:MI:SS''));
        APEX_JSON.write(''ruta_imagen'', rec.ruta_imagen);
        APEX_JSON.close_object;
    END LOOP;
    APEX_JSON.close_array;

EXCEPTION
    WHEN OTHERS THEN
        v_error := SQLERRM;
        HTP.p(''{"status":"error","message":"'' || v_error || ''"}'');
END');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'fotos_publi_api',
      p_pattern        => 'fotos/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fotos_publi_api',
      p_pattern        => 'fotos/:id',
      p_method         => 'GET',
      p_source_type    => 'json/item',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM FOTOS_PUBLI WHERE ID_FOTO=:id');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'fotos_publi_api',
      p_pattern        => 'fotos/:id',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DELETE FROM FOTOS_PUBLI WHERE ID_FOTO=:id;');

  ORDS.DEFINE_MODULE(
      p_module_name    => 'login_api',
      p_base_path      => '/login/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'login_api',
      p_pattern        => 'login',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'login_api',
      p_pattern        => 'login',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  v_id_usuario   USUARIOS.ID_USUARIO%TYPE;
  v_nombre       USUARIOS.NOMBRE%TYPE;
  v_rol          USUARIOS.ROL%TYPE;
  v_estado       USUARIOS.ESTADO_CUENTA%TYPE;
BEGIN
  SELECT ID_USUARIO, NOMBRE, ROL, ESTADO_CUENTA
  INTO v_id_usuario, v_nombre, v_rol, v_estado
  FROM USUARIOS
  WHERE CORREO = :correo
    AND CONTRASENA = :contrasena;

  IF v_estado = ''activo'' THEN
    htp.p(''{
      "status": "success",
      "id_usuario": '' || v_id_usuario || '',
      "nombre": "'' || v_nombre || ''",
      "rol": "'' || v_rol || ''",
      "estado_cuenta": "'' || v_estado || ''"
    }'');
  ELSE
    htp.p(''{
      "status": "error",
      "message": "Tu cuenta está en estado '' || v_estado || ''"
    }'');
  END IF;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    htp.p(''{
      "status": "error",
      "message": "Credenciales inválidas"
    }'');
  WHEN OTHERS THEN
    htp.p(''{
      "status": "error",
      "message": "'' || SQLERRM || ''"
    }'');
END;');

  ORDS.DEFINE_MODULE(
      p_module_name    => 'publicaciones_api',
      p_base_path      => '/publicaciones/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'publicaciones_api',
      p_pattern        => 'publicaciones',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'publicaciones_api',
      p_pattern        => 'publicaciones',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  v_error VARCHAR2(4000);
BEGIN
  OWA_UTIL.mime_header(''application/json'', FALSE);
  HTP.p(''Access-Control-Allow-Origin: *'');
  HTP.p(''Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS'');
  HTP.p(''Access-Control-Allow-Headers: Content-Type'');
  OWA_UTIL.http_header_close;

  APEX_JSON.open_array;
  FOR rec IN (
      SELECT p.id_publi,
             p.id_usuario,
             p.id_colonia,
             c.nombre_colonia,
             p.id_especie,
             p.id_tipo,
             p.id_estado,
             p.nombre_pet,
             p.descripcion,
             TO_CHAR(p.fecha_publi,''YYYY-MM-DD HH24:MI:SS'') AS fecha_publi,
             (SELECT f.ruta_imagen
                FROM fotos_publi f
               WHERE f.id_publi = p.id_publi
                 AND ROWNUM = 1) AS ruta_imagen
      FROM publicaciones p
      LEFT JOIN colonias c ON p.id_colonia = c.id_colonia
  ) LOOP
    APEX_JSON.open_object;
    APEX_JSON.write(''id_publi'', rec.' || 'id_publi);
    APEX_JSON.write(''id_usuario'', rec.id_usuario);
    APEX_JSON.write(''id_colonia'', rec.id_colonia);
    APEX_JSON.write(''nombre_colonia'', rec.nombre_colonia);
    APEX_JSON.write(''id_especie'', rec.id_especie);
    APEX_JSON.write(''id_tipo'', rec.id_tipo);
    APEX_JSON.write(''id_estado'', rec.id_estado);
    APEX_JSON.write(''nombre_pet'', rec.nombre_pet);
    APEX_JSON.write(''descripcion'', rec.descripcion);
    APEX_JSON.write(''fecha_publi'', rec.fecha_publi);
    APEX_JSON.write(''ruta_imagen'', rec.ruta_imagen);
    APEX_JSON.close_object;
  END LOOP;
  APEX_JSON.close_array;

EXCEPTION
  WHEN OTHERS THEN
    v_error := SQLERRM;
    HTP.p(''{"status":"error","message":"'' || v_error || ''"}'');
END;');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'publicaciones_api',
      p_pattern        => 'publicaciones',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  v_id_publi NUMBER;
BEGIN
  OWA_UTIL.mime_header(''application/json'', FALSE);
  OWA_UTIL.http_header_close;

  INSERT INTO publicaciones (
    id_usuario,
    id_colonia,
    id_especie,
    id_tipo,
    id_estado,
    nombre_pet,
    descripcion,
    fecha_publi
  ) VALUES (
    :id_usuario,
    :id_colonia,
    :id_especie,
    :id_tipo,
    1,
    :nombre_pet,
    :descripcion,
    SYSDATE
  )
  RETURNING id_publi INTO v_id_publi;

  APEX_JSON.open_object;
  APEX_JSON.write(''status'', ''success'');
  APEX_JSON.write(''id_publi'', v_id_publi);
  APEX_JSON.write(''message'', ''Publicación creada correctamente'');
  APEX_JSON.close_object;
EXCEPTION
  WHEN OTHERS THEN
    APEX_JSON.open_object;
    APEX_JSON.write(''status'', ''error'');
    APEX_JSON.write(''message'', SQLERRM);
    APEX_JSON.close_object;
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'publicaciones_api',
      p_pattern        => 'publicaciones/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'publicaciones_api',
      p_pattern        => 'publicaciones/:id',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  v_error VARCHAR2(4000);
BEGIN
  -- Encabezados CORS
  OWA_UTIL.mime_header(''application/json'', FALSE);
  HTP.p(''Access-Control-Allow-Origin: *'');
  HTP.p(''Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS'');
  HTP.p(''Access-Control-Allow-Headers: Content-Type'');
  OWA_UTIL.http_header_close;

  -- Construcción del JSON
  APEX_JSON.open_object;
  FOR rec IN (
    SELECT *
    FROM PUBLICACIONES
    WHERE ID_PUBLI = :id
  ) LOOP
    APEX_JSON.write(''id_publi'', rec.id_publi);
    APEX_JSON.write(''id_usuario'', rec.id_usuario);
    APEX_JSON.write(''id_colonia'', rec.id_colonia);
    APEX_JSON.write(''id_especie'', rec.id_especie);
    APEX_JSON.write(''id_tipo'', rec.id_tipo);
    APEX_JSON.write(''id_estado'', rec.id_estado);
    APEX_JSON.write(''nombre_pet'', rec.nombre_pet);
    APEX_JSON.write(''descripcion'', rec.descripcion);
    APEX_JSON.write(''fecha_publi'', TO_CHAR(rec.fecha_publi,''YYYY-MM-DD HH24:MI:SS''));
  END LOOP;
  APEX_JSON.close_object' || ';

EXCEPTION
  WHEN OTHERS THEN
    v_error := SQLERRM;
    HTP.p(''{"status":"error","message":"'' || v_error || ''"}'');
END;');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'publicaciones_api',
      p_pattern        => 'publicaciones/:id',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  v_error VARCHAR2(4000);
BEGIN
  -- Encabezados CORS
  OWA_UTIL.mime_header(''application/json'', FALSE);
  HTP.p(''Access-Control-Allow-Origin: *'');
  HTP.p(''Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS'');
  HTP.p(''Access-Control-Allow-Headers: Content-Type'');
  OWA_UTIL.http_header_close;

  -- Construcción del JSON
  APEX_JSON.open_object;
  FOR rec IN (
    SELECT *
    FROM PUBLICACIONES
    WHERE ID_PUBLI = :id
  ) LOOP
    APEX_JSON.write(''id_publi'', rec.id_publi);
    APEX_JSON.write(''id_usuario'', rec.id_usuario);
    APEX_JSON.write(''id_colonia'', rec.id_colonia);
    APEX_JSON.write(''id_especie'', rec.id_especie);
    APEX_JSON.write(''id_tipo'', rec.id_tipo);
    APEX_JSON.write(''id_estado'', rec.id_estado);
    APEX_JSON.write(''nombre_pet'', rec.nombre_pet);
    APEX_JSON.write(''descripcion'', rec.descripcion);
    APEX_JSON.write(''fecha_publi'', TO_CHAR(rec.fecha_publi,''YYYY-MM-DD HH24:MI:SS''));
  END LOOP;
  APEX_JSON.close_object' || ';

EXCEPTION
  WHEN OTHERS THEN
    v_error := SQLERRM;
    HTP.p(''{"status":"error","message":"'' || v_error || ''"}'');
END;');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'publicaciones_api',
      p_pattern        => 'publicaciones/:id',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  v_error VARCHAR2(4000);
BEGIN
  -- Encabezados CORS
  OWA_UTIL.mime_header(''application/json'', FALSE);
  HTP.p(''Access-Control-Allow-Origin: *'');
  HTP.p(''Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS'');
  HTP.p(''Access-Control-Allow-Headers: Content-Type'');
  OWA_UTIL.http_header_close;

  -- Eliminación
  DELETE FROM PUBLICACIONES
  WHERE ID_PUBLI = :id;

  IF SQL%ROWCOUNT > 0 THEN
    HTP.p(''{"status":"success","message":"Publicación eliminada"}'');
  ELSE
    HTP.p(''{"status":"error","message":"No se encontró la publicación"}'');
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    v_error := SQLERRM;
    HTP.p(''{"status":"error","message":"'' || v_error || ''"}'');
END;');

  ORDS.DEFINE_MODULE(
      p_module_name    => 'tipos_publi_api',
      p_base_path      => '/tipos_publi/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'tipos_publi_api',
      p_pattern        => 'tipos_publi',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'tipos_publi_api',
      p_pattern        => 'tipos_publi',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM TIPOS_PUBLI');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'tipos_publi_api',
      p_pattern        => 'tipos_publi',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'INSERT INTO TIPOS_PUBLI (NOMBRE) VALUES (:NOMBRE);');

  ORDS.DEFINE_MODULE(
      p_module_name    => 'usuarios_api',
      p_base_path      => '/usuarios/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'usuarios_api',
      p_pattern        => 'usuarios',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'usuarios_api',
      p_pattern        => 'usuarios',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM USUARIOS');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'usuarios_api',
      p_pattern        => 'usuarios',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
  INSERT INTO USUARIOS (
    NOMBRE,
    APELLIDO,
    CORREO,
    CONTRASENA,
    TELEFONO,
    DIRECCION,
    ID_COLONIA,
    ROL,
    ESTADO_CUENTA,
    FECHA_REGISTRO
  )
  VALUES (
    :nombre,
    :apellido,
    :correo,
    :contrasena,
    :telefono,
    :direccion,
    :id_colonia,
    :rol,
    :estado_cuenta,
    SYSTIMESTAMP
  );

  htp.p(''{"status":"success","message":"Usuario registrado correctamente"}'');
EXCEPTION
  WHEN OTHERS THEN
    htp.p(''{"status":"error","message":"'' || SQLERRM || ''"}'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'usuarios_api',
      p_pattern        => 'usuarios/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'usuarios_api',
      p_pattern        => 'usuarios/:id',
      p_method         => 'GET',
      p_source_type    => 'json/item',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM USUARIOS WHERE ID_USUARIO=:id');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'usuarios_api',
      p_pattern        => 'usuarios/:id',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'UPDATE USUARIOS
SET NOMBRE=:NOMBRE, APELLIDO=:APELLIDO, CORREO=:CORREO, CONTRASENA=:CONTRASENA,
    TELEFONO=:TELEFONO, DIRECCION=:DIRECCION, ID_COLONIA=:ID_COLONIA, ROL=:ROL
WHERE ID_USUARIO=:id;');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'usuarios_api',
      p_pattern        => 'usuarios/:id',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DELETE FROM USUARIOS WHERE ID_USUARIO=:id;');

  ORDS.CREATE_ROLE(
      p_role_name=> 'oracle.dbtools.role.autorest.MIGO_USER');
  ORDS.CREATE_ROLE(
      p_role_name=> 'oracle.dbtools.role.autorest.any.MIGO_USER');
  l_roles(1) := 'oracle.dbtools.auth.roles.builtin.VecDB';
  l_patterns(1) := '/vecdb/*';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'oracle.dbtools.auth.privileges.builtin.VecDB',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => NULL,
      p_description    => NULL,
      p_comments       => NULL); 

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;

  l_roles(1) := 'oracle.dbtools.autorest.any.schema';
  l_roles(2) := 'oracle.dbtools.role.autorest.MIGO_USER';
  l_patterns(1) := '/metadata-catalog/*';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'oracle.dbtools.autorest.privilege.MIGO_USER',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'MIGO_USER metadata-catalog access',
      p_description    => 'Provides access to the metadata catalog of the objects in the MIGO_USER schema.',
      p_comments       => NULL); 

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;

  l_roles(1) := 'SODA Developer';
  l_patterns(1) := '/soda/*';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'oracle.soda.privilege.developer',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => NULL,
      p_description    => NULL,
      p_comments       => NULL); 

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;

  ORDS.FINALIZE_IMPORT(
      p_prune => FALSE,
      p_objects => null);

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;